### ISSUE TITLE
Compiled distributable?

### ISSUE THREAD

**Issue by cheapsteak** [mattdesl/gsap-promise#1]
Want to drop this into jsfiddles/codepens

**Comment by mattdesl** [comment]
The only trouble is that it introduces another avenue I need to maintain and update with new versions. Adding a bundle to git also adds some bloat. 

Have you seen this?
http://requirebin.com/

**Comment by cheapsteak** [comment]
Yeah I took a look but it doesn't have the nice things that codepen has (Slim/Jade instead of HTML, Stylus/Sass instead of CSS, ES6 instead of ES5)  

Although I wonder if I could require a module there and load the output externally?

**Comment by cheapsteak** [comment]
requirebin broke :(

**Comment by cheapsteak** [comment]
brcdn.org seems to do the trick
