### ISSUE TITLE
from/to states passed in should not be mutated

### ISSUE THREAD

**Issue by cheapsteak** [mattdesl/gsap-promise#5]
Problem: 

```
import animate from 'gsap-promise';

const from = {opacity: 0};
const to = {opacity: 1};

Promise.all([
    animate.fromTo(el1, 0.5, from, to),
    animate.fromTo(el2, 0.5, from, to),
])

```

The first promise never resolves because the onComplete is overwritten by the second call

This would be solved if the object is shallow cloned before having options added on by the library
#### Current workaround

Defensively clone everything passed into gsap-promise

```
Promise.all([
    animate.fromTo(el1, 0.5, {...from}, {...to}),
    animate.fromTo(el2, 0.5, {...from}, {...to}),
])
```

**Comment by mattdesl** [comment]
:+1: We can use [object-assign](https://github.com/sindresorhus/object-assign) for this.

**Comment by cheapsteak** [comment]
pushed fix to master along with new test
would adding a dependency justify bumping a minor version or should it just be a patch?

**Comment by mattdesl** [comment]
Just a patch since the API didn't change and there are no new features added
